name: 'Build with Code Composer Studio'
description: 'Initialize a CCS workspace and build project configurations'
author: 'Orace'
branding:
  icon: 'box'
  color: 'red'
inputs:
  product_family:
    description: 'TI product family (e.g., c28)'
    required: true
  project_path:
    description: 'Relative path to the CCS project'
    required: true
  configurations:
    description: 'Semicolon-separated list of build configurations'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/orace/ccsbuild-c28:0.3'
  entrypoint: '/entrypoint.sh'
