name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        product_family: [c28]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image for ${{ matrix.product_family }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.product_family }}
          push: true
          tags: ghcr.io/orace/ccsbuild-${{ matrix.product_family }}:0.2
          
